packages:
  - apps/*
  - packages/*

catalog:
  # Auth
  "@convex-dev/better-auth": "^0.8.6"
  "better-auth": "1.3.8"

  # UI & Icons
  "@iconify/react": "^6.0.2"
  "class-variance-authority": "^0.7.1"
  "clsx": "^2.1.1"
  "lucide-react": "^0.544.0"
  "radix-ui": "^1.4.3"
  "sonner": "^2.0.7"
  "tailwind-merge": "^3.3.1"
  "tw-animate-css": "^1.4.0"

  # Forms & Validation
  "@tanstack/react-form": "^1.23.5"
  "zod": "^4.1.11"

  # Convex & Backend
  "convex": "^1.27.3"

  # Utilities
  "es-toolkit": "^1.39.10"
  "get-youtube-id": "^1.0.1"
  "zustand": "^5.0.8"

  # Media & Animation
  "@vapi-ai/web": "^2.4.0"
  "motion": "^12.23.22"
  "react-player": "^2.16.0"

  # Next.js & React
  "next": "15.5.4"
  "next-themes": "^0.4.6"
  "react": "19.1.1"
  "react-dom": "19.1.1"

  # AI & ML
  "@ai-sdk/openai": "^2.0.38"
  "@convex-dev/agent": "^0.2.10"
  "@mendable/firecrawl-js": "^4.3.6"

  # HTTP & Caching
  "axios": "1.12.2"
  "lru-cache": "^11.2.2"

  # Text Processing
  "common-tags": "^1.8.2"

  # Dev Dependencies
  "@tailwindcss/postcss": "^4.1.13"
  "@types/common-tags": "^1.8.4"
  "@types/node": "22.18.7"
  "@types/react": "19.1.16"
  "@types/react-dom": "19.1.9"
  "tailwindcss": "^4.1.13"
  typescript: ^5.9.3

  immer: ^10.1.3


onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
